/* eslint-disable linebreak-style */
const KeySetRu = () => [
  [
    { key: 'ё', bgc: true },
    { key: '1', span: '!' },
    { key: '2', span: '"' },
    { key: '3', span: ';' },
    { key: '4', span: '%' },
    { key: '5', span: ':' },
    { key: '6', span: '?' },
    { key: '7', span: '?' },
    { key: '8', span: '*' },
    { key: '9', span: '(' },
    { key: '0', span: ')' },
    { key: '-', span: '_' },
    { key: '=', span: '+' },
    { key: 'Backspace', width: '123px', bgc: true },
  ],
  [
    { key: 'Tab', width: '60px', bgc: true },
    { key: 'й' },
    { key: 'ц' },
    { key: 'у' },
    { key: 'к' },
    { key: 'е' },
    { key: 'н' },
    { key: 'г' },
    { key: 'ш' },
    { key: 'щ' },
    { key: 'з' },
    { key: 'х' },
    { key: 'ъ' },
    { key: '\\', span: '/' },
    { key: 'del', width: '55px', bgc: true },
  ],
  [
    { key: 'Caps Lock', width: '121px', bgc: true },
    { key: 'ф' },
    { key: 'ы' },
    { key: 'в' },
    { key: 'а' },
    { key: 'п' },
    { key: 'р' },
    { key: 'о' },
    { key: 'л' },
    { key: 'д' },
    { key: 'ж' },
    { key: 'э' },
    { key: 'Enter', width: '106px', bgc: true },
  ],
  [
    { key: 'Shift', width: '179px', bgc: true },
    { key: 'я' },
    { key: 'ч' },
    { key: 'с' },
    { key: 'м' },
    { key: 'и' },
    { key: 'т' },
    { key: 'ь' },
    { key: 'б' },
    { key: 'ю' },
    { key: '.', span: ',' },
    { key: '&#9650;', bgc: true },
    { key: 'Shift', bgc: true },
  ],
  [
    { key: 'Ctrl', width: '80px', bgc: true },
    { key: 'Meta', bgc: true },
    { key: 'Alt', bgc: true },
    { key: ' ', width: '339px' },
    { key: 'Alt', bgc: true },
    { key: 'Ctrl', width: '80px', bgc: true },
    { key: '&#9668;', bgc: true },
    { key: '&#9660;', bgc: true },
    { key: '&#9658;', bgc: true },
  ],
];

export default KeySetRu;
